### ISSUE TITLE
Audacity.munki recipe not working

### ISSUE THREAD

**Issue by grahampugh** [autopkg/timsutton-recipes#10]
Here's the error:

05/02/2015 14:47:27.923 AutoPkgr[14314]: 
The following recipes failed:
    Audacity.munki
        Unknown processor 'com.github.jessepeterson.munki.GrandPerspective/SourceForgeURLProvider'.

Nothing downloaded, packaged or imported.

**Comment by timsutton** [comment]
It should be pretty clear what's going on here. This repo's README also explicitly states that the Audacity recipes require Jesse Peterson's repo.

**Comment by grahampugh** [comment]
Hi Tim,




OK, I see. Unfortunately the readme’s aren’t visible from Autopkgr, but I’ll be sure to go checking in future.




Cheers, Graham





Dr Graham R PughIT Support Specialist

University of Bristol / Zone D

Subject Specialist - Maths

Mac System Administration Specialist

**Comment by timsutton** [comment]
We've also discussed before the idea of a recipe being able to declare a "required repo" somewhere in the recipe, so that AutoPkg can give a more helpful error message - so perhaps this might make its way into the next version.
