### ISSUE TITLE
Komodo Edit: Could not retrieve URL

### ISSUE THREAD

**Issue by flammable** [autopkg/timsutton-recipes#11]
Hey Tim -

I have AutoPkgr running our list of recipes on a schedule.  On almost every AutoPkg run, I get this error:

Error in local.munki.KomodoEdit: Processor: URLTextSearcher: Error: Could not retrieve URL: http://komodoide.com/download/edit-osx

Sometimes, the error isn't present at all, and sometimes, the recipe downloads a new version of Komodo Edit.  Most of the time, I see the above error, though.  Any idea why it's failing so often?  Whenever I try the URL in my browser, it always works without issue.

Thanks!

Mike

**Comment by timsutton** [comment]
Nothing jumps out to me as to the reason. I run this recipe via a list several times a day and I've never actually seen it error. The page seems to be served via a GitHub.com server. One little thing I noticed is that there's a redirect on the URL without a trailing slash, so I added it to avoid the redirected request. But in your case I'm not sure that will change anything.

It could simply be a GitHub CDN issue, though if you're really curious you might try directing your traffic through a local proxy like Charles to see if you can identify why the server seems to fail to respond. AutoPkg uses Python's standard library urllib2 for URL requests, which respects environment variables like `http_proxy` and `https_proxy`.

**Comment by flammable** [comment]
Thanks, Tim.  As far as I know, there is nothing blocking Komodo's website (or GitHub) on our network.  The recipe is run every 8 hours, as part of a larger list of recipes (I'm using AutoPkgr, but I'm fairly sure I saw the same errors when I was running AutoPkg manually).  Almost all of the time, I see the above error.  On a rare occasion, it downloads a new version, or there is no error message at all.

I've never worked with Charles before, but I'll see what I can find.  It's not a huge issue, was mostly wondering if you were seeing the same thing or not.  Thanks for the recipe and the assistance!

**Comment by flammable** [comment]
Odd - for some reason, the errors have stopped for a couple of weeks now.  I'm not sure if adding the user agent (c2b3e3659bba43030baa9cb920676f3d2f6c069c) did it, or if it was a network issue on my end, but I'm going to close this issue.

Thanks for taking a look! :)
