### ISSUE TITLE
Audacity moved from SourceForge to Fosshub

### ISSUE THREAD

**Issue by klou** [autopkg/timsutton-recipes#13]
Looks like Audacity moved it's repository to either Fosshub or OldFoss.

The exodus from SourceForge continues.

**Comment by timsutton** [comment]
Thanks! I probably won't have time to take a look at this for a little while, but it looks like simply reverting the code that switched from URLTextSearcher on their main download page to using SourceForge might be enough. Their page seems to redirect to fosshub for me. Previously there was an issue where different page loads would return different downloads with different ETags, meaning the recipe would frequently re-download the installer.

Anyone is welcome to test and verify a fix in the meantime before I get to it.

**Comment by klou** [comment]
Yes, it looks like the download provider change is "official."

From their forums:
>    Norm Mast wrote:
>>    I am doing a total download of the program here....hoping to clear up some audio issues I kept having. From the Audacity page when I click to download for my Windows XP OS I get taken to a differant page, with the name Foss Hub showing . A little uncomfortable seing this....is this the right page to be at?
>
>
>Yes. Fosshub is our download partner that hosts the Audacity downloads.
>
>Gale

Reverting the SFProcessor and relinking to http://www.fosshub.com/Audacity.html would probably do it, but I'm not sure about the ETags.
