### ISSUE TITLE
SparkleUpdateInfoProvider error | iStopMotion3.download

### ISSUE THREAD

**Issue by jazzace** [autopkg/timsutton-recipes#16]
I've been having the iStopMotion3.download recipe fail for me for quite a while and I've finally got a chance to do some digging. This error comes up when accessing the Sparkle feed using SparkleUpdateInfoProvider:

````
SparkleUpdateInfoProvider
Can't open URL https://sparkle.boinx.com/appcast.lasso?locale=en_US&feedtype=1&lang=en&appName=iStopMotion&appID=ISTO&versionString=3.0
Failed.
````

Yet when I take that generated URL and try to download it using manual means (e.g., highlight it and use Services to Download URL), I get what looks like a perfectly good rss feed file. Since the feed link is https, I'm wondering if this is the same side effect that led to the creation of the CURLDownloader and CURLTextSearcher variants. Or perhaps not. Regardless, I can't get the recipe to work. Tested on OS X 10.10.5.

**Comment by timsutton** [comment]
This bugged me for a while too. Looks like it was as simple as just setting a different `User-Agent`, and I just picked `curl` because it worked.
