### ISSUE TITLE
Autopkg unable to create DMG

### ISSUE THREAD

**Issue by BaddMann** [autopkg/timsutton-recipes#20]
Still Googling around and it appears to be an OSX issue.
Your recipe is the only one I'm seeing this issue with right now, so I thought I'd give you heads up.

error:
hdiutil: create failed - error -5341

**Comment by timsutton** [comment]
This is a known bug with `hdiutil`, yes, and there's a `dmg_megabytes` input variable we added as a workaround to fix problematic recipes. But you didn't specify the recipe that's failing..

**Comment by gregneagle** [comment]
_your_ recipe!

**Comment by BaddMann** [comment]
I'm sorry, not that familiar with Github issue tracking, thought that
detail was attached to issue as I filed it from the receipt location.

It's the 5jsEditor.munki.recipe
<https://github.com/autopkg/timsutton-recipes/blob/master/Processing/p5jsEditor.munki.recipe>

**Comment by timsutton** [comment]
Thanks for reporting - since this works on 10.11 this seems to be the usual bug with 10.9's (and maybe 10.10's?) `hdiutil`.
