### ISSUE TITLE
MXF4macPlayer Recipes Broke, hamburgpromedia.com Site Gone

### ISSUE THREAD

**Issue by foigus** [autopkg/timsutton-recipes#21]
FWIW the MXF4macPlayer recipes no longer work since hamburgpromedia.com no longer resolves.  Apparently Apple may have bought them sometime back and integrated parts of their products into FCPX:

http://www.fcp.co/final-cut-pro/articles/1486-hamburg-pro-media-withdraw-final-cut-pro-x-products

**Comment by timsutton** [comment]
Thanks, I didn't know this. I'll be deleting the recipes in that case - doesn't look like there's any chance this recipe will be of any use any more.
