### ISSUE TITLE
REDCINE-X Pro Munki.

### ISSUE THREAD

**Issue by BaddMann** [autopkg/timsutton-recipes#23]
I'm Getting this code in a fake pkg within the Download Cache Folder:

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>software/rcx/mac/release/40.40706/REDCINE-X_PRO_Build_40.pkg</Key><RequestId>9F14$

Researching more.....

**Comment by BaddMann** [comment]
NeverMind it's the site's fault, I'm not sure you can account for it.....


Can you?

**Comment by timsutton** [comment]
How did you confirm the site has an issue? The version 40 download works for me from the site, but that's not what this recipe currently uses anyway - it uses the app's internal Sparkle feed. So for all I can tell the recipe is currently broken.

**Comment by BaddMann** [comment]
I download fine from the site, but thier sparkle feed url for Build 40 is missing the ".0.pkg" at the end of the URL
