### ISSUE TITLE
Audacity.download.recipe -- URLTextSearcher: Error: No match found on URL

### ISSUE THREAD

**Issue by childrss** [autopkg/timsutton-recipes#29]
Looked into this briefly and couldn't figure out why it was erring out..

$ autopkg run -v Audacity.download

Processing Audacity.download...
URLTextSearcher
URLTextSearcher: Found matching text (first_url): https://www.fosshub.com/Audacity.html/audacity-macosx-ub-2.1.2.dmg
URLTextSearcher: Found matching text (match): https://www.fosshub.com/Audacity.html/audacity-macosx-ub-2.1.2.dmg
URLTextSearcher
URLTextSearcher: Found matching text (data): https://download.fosshub.com/Protected/expiretime=1472744203;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/d81f644a8809142f4d2e280b171452bcb132781c6ed6a9bc11e0305c0c0d4acc/Audacity/audacity-macosx-ub-2.1.2.dmg
URLTextSearcher: Found matching text (match): https://download.fosshub.com/Protected/expiretime=1472744203;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/d81f644a8809142f4d2e280b171452bcb132781c6ed6a9bc11e0305c0c0d4acc/Audacity/audacity-macosx-ub-2.1.2.dmg
URLTextSearcher
No match found on URL: http://www.fosshub.com/gensLink/https://download.fosshub.com/Protected/expiretime=1472744203;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/d81f644a8809142f4d2e280b171452bcb132781c6ed6a9bc11e0305c0c0d4acc/Audacity/audacity-macosx-ub-2.1.2.dmg
Failed.
Receipt written to /Library/AutoPkg/Cache/com.github.timsutton.download.audacity/receipts/Audacity-receipt-20160901-103248.plist

The following recipes failed:
    Audacity.download
        Error in com.github.timsutton.download.audacity: Processor: URLTextSearcher: Error: No match found on URL: http://www.fosshub.com/gensLink/https://download.fosshub.com/Protected/expiretime=1472744203;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/d81f644a8809142f4d2e280b171452bcb132781c6ed6a9bc11e0305c0c0d4acc/Audacity/audacity-macosx-ub-2.1.2.dmg

Nothing downloaded, packaged or imported.

**Comment by timsutton** [comment]
Looking at the Git history of this Audacity.download recipe, and the number of versions I have (5) in my Munki repo since July 2014, there are more commits fixing the recipe than there are released versions. 😞 

It doesn't mean I wouldn't like to get this recipe fixed, just that I'm less motivated to do so right now because of how infrequently they release new versions, and how fosshub.com changes its website logic so frequently (somewhat related to a security breach that happened in the last month or so.

**Comment by gregneagle** [comment]
Consider putting the recipe up for adoption and see if anyone else wants to take over its maintenance. The point of autopkg is to save time -- if maintaining the recipe doesn't ultimately save you time or make you money --  there's little point to it.

**Comment by childrss** [comment]
No rush or demand on my account.  Just logging it.  

If you've a motivational beer (or other tasty adult beverage) button somewhere, let me know ;-)  -- still no rush even with the beverage ;-)

**Comment by n8felton** [comment]
😞
I'll take a look at this again on Monday.

**Comment by timsutton** [comment]
@n8felton Don't be disappointed, it's fixed!
