### ISSUE TITLE
Error in local.munki.Go: Processor: CodeSignatureVerifier: Error: Mismatch in authority names.

### ISSUE THREAD

**Issue by paulbloch** [autopkg/timsutton-recipes#32]
sysadmin@beta: ~/autopkg 479$ autopkg run -v go.munki
Processing go.munki...
URLTextSearcher
URLTextSearcher: Found matching text (url): https://storage.googleapis.com/golang/go1.7.4.darwin-amd64.pkg
URLTextSearcher: Found matching text (version): 1.7.4
URLTextSearcher: Found matching text (match): https://storage.googleapis.com/golang/go1.7.4.darwin-amd64.pkg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/sysadmin/Library/AutoPkg/Cache/local.munki.Go/downloads/go1.7.4.darwin-amd64.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "go1.7.4.darwin-amd64.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Google, Inc. (EQHXZ8M8AV)
CodeSignatureVerifier:        SHA1 fingerprint: DC 33 45 6C 34 D9 FD F8 04 3E A3 C5 FA B0 84 A4 6B 4D A0 B5
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Mismatch in authority names
CodeSignatureVerifier: Expected: Developer ID Installer: Google Inc. -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: Google, Inc. (EQHXZ8M8AV) -> Developer ID Certification Authority -> Apple Root CA
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
Receipt written to /Users/sysadmin/Library/AutoPkg/Cache/local.munki.Go/receipts/go-receipt-20161202-100711.plist

The following recipes failed:
    go.munki
        Error in local.munki.Go: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Nothing downloaded, packaged or imported.

**Comment by timsutton** [comment]
Thanks! If anyone wants to submit a PR I'll merge it, but otherwise may need to wait a day or two.

**Comment by timsutton** [comment]
I lied!
