### ISSUE TITLE
Max7 download regex needs to be more restrictive 

### ISSUE THREAD

**Issue by orbsmiv** [autopkg/timsutton-recipes#36]
The regex is currently returning the following as the URL:

`'https://cycling74-web-assets.s3.amazonaws.com/images/photos/max-with-bens-studio.jpg"/><meta data-react-helmet="true" name="viewport" content="width=device-width, initial-scale=1.0"/><meta data-react-helmet="true" name="description" content="Thanks for downloading Max."/><meta data-react-helmet="true" http-equiv="refresh" content="2;url=https://akiaj5esl75o5wbdcv2a-maxmspjitter.s3.amazonaws.com/Max733_170301.dmg'`

**Comment by timsutton** [comment]
I think they must be still doing some tweaking on their site. I likely can't look at this until next week but I'd be happy to merge any PRs. I usually find in these cases that using the non-greedy matching operator `?` is what's needed.

**Comment by timsutton** [comment]
This was addressed in #37.
