### ISSUE TITLE
Error: Could not get a download URL: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by rfitzwater** [autopkg/timsutton-recipes#43]
I'm getting the errors below for DaVinciResolve and DesktopVideo.  Checking for a quick fix before I dig deeper.

-Rhon
RECIPE | MESSAGE
-- | --
local.munki.DesktopVideo | Error in local.munki.DesktopVideo: Processor: com.github.timsutton.download.davinciresolvelite11/BlackMagicURLProvider: Error: Could not get a download URL: HTTP Error 400: Bad Request
local.munki.DaVinciResolve12 | Error in local.munki.DaVinciResolve12: Processor: BlackMagicURLProvider: Error: Could not get a download URL: HTTP Error 400: Bad Request

**Comment by timsutton** [comment]
I've noticed this as well. The error seems to happen in the step where we request a URL to fake the registration submission. Some more digging will be needed to see what has changed with their website for how this step works.

**Comment by timsutton** [comment]
Hopefully 0dcf51f resolves this. It looks like a valid country and "state" are now required, and I've updated the recipe descriptions to clarify this.

**Comment by rfitzwater** [comment]
I'm still getting the "Could not get a download URL: HTTP Error 400: Bad Request" error.  I removed then recreated a local recipe.  Am I missing some steps?

**Comment by rfitzwater** [comment]
Ignore last comment.  I had a typo in State info.  Corrected it and now recipe is running fine.  Thanks!
