### ISSUE TITLE
RE: timsutton-recipes/Figure53/QLab3.munki.recipe

### ISSUE THREAD

**Issue by elflames** [autopkg/timsutton-recipes#52]
It appears when the Qlab3.download.recipe was updated with the addition of /Applications the munki recipe broke when trying to do a munkiimport as there was no application anymore at the root of the DMG.
Munkimport is failing with "Error in local.munki.CDU-QLab3: Processor: MunkiImporter: Error: creating pkginfo for /Users/autopkgr/Library/AutoPkg/Cache/local.munki.CDU-QLab3/QLab3.dmg failed: Could not find a supported installer item in /Users/autopkgr/Library/AutoPkg/Cache/local.munki.CDU-QLab3/QLab3.dmg!"

by adding /Applications to the dmg_root key munkiimport works again.

Figured I would open this issue, incase this was a slight oversight?

cheers for all your goodies over the years mate.

**Comment by timsutton** [comment]
Sounds like you've identified the issue, thanks! Would you be able to contribute a working PR?

**Comment by nescom-it** [comment]
I was getting the same error as elflames and adding /Applications to the dmg_root resolved my issue as well : 

The following recipes failed:
    /Users/bs_autopkg/Library/AutoPkg/RecipeOverrides/QLab3.munki.recipe
        Error in local.munki.QLab3: Processor: MunkiImporter: Error: creating pkginfo for /Users/bs_autopkg/Library/AutoPkg/Cache/local.munki.QLab3/QLab.dmg failed: Could not find a supported installer item in /Users/bs_autopkg/Library/AutoPkg/Cache/local.munki.QLab3/QLab.dmg!

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Description</key>
    <string>Downloads the latest version of QLab 3 and imports into Munki.</string>
    <key>Identifier</key>
    <string>com.github.timsutton.munki.qlab3</string>
    <key>Input</key>
    <dict>
        <key>NAME</key>
        <string>QLab3</string>
        <key>MUNKI_REPO_SUBDIR</key>
        <string>apps/%NAME%</string>
        <key>pkginfo</key>
        <dict>
            <key>catalogs</key>
            <array>
                <string>testing</string>
            </array>
            <key>description</key>
            <string>QLab provides live show control for your Mac. Create media designs for theatre, dance, composition, installation, and more. Play back audio, video, and MIDI from a single workspace.</string>
            <key>display_name</key>
            <string>QLab 3</string>
            <key>name</key>
            <string>%NAME%</string>
            <key>unattended_install</key>
            <true/>
        </dict>
    </dict>
    <key>MinimumVersion</key>
    <string>0.2.0</string>
    <key>ParentRecipe</key>
    <string>com.github.timsutton.download.qlab3</string>
    <key>Process</key>
    <array>
        <dict>
            <key>Processor</key>
            <string>MunkiPkginfoMerger</string>
        </dict>
        <dict>
            <key>Processor</key>
            <string>DmgCreator</string>
            <key>Arguments</key>
            <dict>
                <key>dmg_root</key>
                <string>%RECIPE_CACHE_DIR%/%NAME%/Applications</string>
                <key>dmg_path</key>
                <string>%RECIPE_CACHE_DIR%/%NAME%.dmg</string>
            </dict>
        </dict>
        <dict>
            <key>Arguments</key>
            <dict>
                <key>pkg_path</key>
                <string>%dmg_path%</string>
                <key>repo_subdirectory</key>
                <string>%MUNKI_REPO_SUBDIR%</string>
            </dict>
            <key>Processor</key>
            <string>MunkiImporter</string>
        </dict>
    </array>
</dict>
</plist>
`

**Comment by timsutton** [comment]
Thanks for confirming @nescom-it! Would anyone be willing to submit those changes as a PR so that we can merge a fix?

Tangentially, is Figure53 still supporting Qlab3? Been a while since I’ve worked with it and before I left my workplace which used it we had moved onto Qlab4.

**Comment by nescom-it** [comment]
I have created a PR for this fix. Figure 53 is still supporting Qlab 3 as of February 5, 2018. Thanks again.

**Comment by timsutton** [comment]
Closed in #58.
