### ISSUE TITLE
AutoDMG prompting for new updated when latest is fetched from recipe

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/timsutton-recipes#6]
What sounds like a CFBundleVersion vs. CFBundleShortVersionString I think is happening. AutoDMG's Sparkle(?) updater wants to update to AutoDMG v1.5 build 375, but the recipe still thinks my 1.5b 355 that's installed is current.

**Comment by timsutton** [comment]
Old issue :). AutoDMG's obviously retired at this point. Those were the good days.
