### ISSUE TITLE
Go.download CodeSignatureVerifier mismatch in authority names.

### ISSUE THREAD

**Issue by gregneagle** [autopkg/timsutton-recipes#67]
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "go1.13.darwin-amd64.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Google LLC (EQHXZ8M8AV)
CodeSignatureVerifier:        SHA1 fingerprint: F8 6C 50 3A B4 14 C7 D4 C2 24 0C 35 FF F1 F0 A3 0D B8 63 1E
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Mismatch in authority names
CodeSignatureVerifier: Expected: Developer ID Installer: Google, Inc. (EQHXZ8M8AV) -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: Google LLC (EQHXZ8M8AV) -> Developer ID Certification Authority -> Apple Root CA
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.

**Comment by timsutton** [comment]
Fixed in #62.
