### ISSUE TITLE
Error parsing XML from appcast feed

### ISSUE THREAD

**Issue by JMichaelAdams** [autopkg/timsutton-recipes#70]
Error parsing XML from appcast feed.
Failed.
Receipt written to /Users/bs_autopkg/Library/AutoPkg/Cache/local.munki.REDCINE-XPRO/receipts/REDCINE-XPRO.munki-receipt-20191024-143352.plist

The following recipes failed:
    /Users/bs_autopkg/Library/AutoPkg/RecipeOverrides/REDCINE-XPRO.munki.recipe
        Error in local.munki.REDCINE-XPRO: Processor: SparkleUpdateInfoProvider: Error: Error parsing XML from appcast feed.

**Comment by JMichaelAdams** [comment]
I found the iss in my override. Sorry for wasting your time

**Comment by timsutton** [comment]
No problem!
