### ISSUE TITLE
BarebonesURLProvider.py needs updating for AutoPkg 2.0

### ISSUE THREAD

**Issue by jazzace** [autopkg/timsutton-recipes#72]
AutoPkg 2.0 uses Python 3. As best as I can read the error messages, Python 3 does not support `urllib2`, which the BarebonesURLProvider custom processor requires.

**Comment by nmcspadden** [comment]
There is no BareBonesURLProvider in this repo, unless I'm completely blind. The only one I know of is in autopkg-recipes, which I updated: https://github.com/autopkg/recipes/blob/master/Barebones/BarebonesURLProvider.py

**Comment by jazzace** [comment]
You're right, of course. I transposed some information between failed recipes.
