### ISSUE TITLE
Code Signature changed for Processing.download

### ISSUE THREAD

**Issue by eshirk** [autopkg/timsutton-recipes#91]
Looks like the Processing.app code signature has been changed, to:

identifier "org.processing.four" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "8SBRM6J77J"

**Comment by timsutton** [comment]
Thanks. Maybe we'll want to wait until Processing 4 is out of beta, since the download recipe pulls the 3.x stable versions still. Alternatively if someone would like to create a new Processing4 recipe that can pull the betas (and later once it's stable) I'd be open to that as well.

**Comment by timsutton** [comment]
With Processing 4 out, and the comments in this issue: https://github.com/autopkg/timsutton-recipes/pull/98 – I'm going to close this one, as there's a stable separate Processing 4 recipe now available.

**Comment by eshirk** [comment]
Thanks, Tim. Would you by any chance be open to switching your Processing.munki recipe to use jazzace's Processing4.download recipe, since he doesn't maintain a Munki recipe?
